name: CI & Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Instalar Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.6'

      - name: Instalar dependências
        run: go mod tidy

      - name: Build
        run: go build -v ./...

      - name: Testes
        run: go test ./...

  release:
    name: Release com GoReleaser
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    needs: build-test

    steps:
      - name: Checkout código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Instalar Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.6'

      - name: Instalar GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
