name: CI & Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main

jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.6'

      - name: Build
        run: go build -v ./...

      - name: Testes (se houver)
        run: go test ./... || true

  release:
    name: Release com GoReleaser
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    needs: build-test

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20

      - name: Instalar GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
